### ISSUE TITLE
network gova11y declared as external, but could not be found

### ISSUE THREAD

**Issue by mgifford** [GovA11y/getting-started#4]
Trying to get getting started going:  
  
`% pwd`  
`~/getting-started/docker`  
`% docker-compose -f actors-only.yml up`

I got this error:  
`network gova11y declared as external, but could not be found`

**Comment by TheBoatyMcBoatFace** [comment]
You need to have the `gova11y` network setup before running it. 

Run the below
```bash
docker network create --driver bridge --subnet=10.50.0.0/16 --ip-range=10.50.0.0/24 --gateway=10.50.0.1 --attachable --scope local gova11y
```

If you get a permissions error, run the below
```bash
sudo docker network create --driver bridge --subnet=10.50.0.0/16 --ip-range=10.50.0.0/24 --gateway=10.50.0.1 --attachable --scope local gova11y
```

**Comment by mgifford** [comment]
That works! Thanks.
